In [63]:
import pandas as pd
import numpy as np

In [64]:
df = pd.read_csv(
    r"C:\Users\sujal\workie competitor analysis\workie_competitor_raw.csv"
)

df.head()

,record_id,company,city,location,area,workspace_type,target_segment,seat_capacity,price_per_seat_month,day_pass_price,...,air_conditioning,printing,event_space,community_events,managed_office,build_to_suit,enterprise_solution,data_source,data_date,data_type
0,1164,Regus,Indore,Regus Indore,Vijay Nagar,Private Office,Freelancer,10,18300,465,...,Yes,No,Yes,YES,NaN,Y,Yes,Company Website,2026-09-27,SYNTHETIC_PRACTICE_RECORD
1,1034,BizNest,Indore,BizNest Palasia,New Palasia,Hot Desk,Enterprise,60,6100,886 + GST,...,Yes,Yes,Yes,NaN,NO,No,NO,Public Listing,2026-09-29,SYNTHETIC_PRACTICE_RECORD
2,1016,Nexus Spaces,Indore,Vishal Cube,Janjeerwala Square,Private Office,SME,10,"₹11,500",1016,...,Yes,Yes,YES,yes,Yes,No,NaN,Company Website,2026-09-29,SYNTHETIC_PRACTICE_RECORD
3,1323,IndiQube,Indore,IndiQube Indore,Vijay Nagar,Private Office,Enterprise,8,14700,540,...,Yes,Yes,no,No,NaN,NaN,No,Marketplace Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD
4,1058,Nexus Spaces,Indore,Nexus Hub,Vijay Nagar,Private Office,Remote Team,4,8200,811,...,Yes,NaN,Yes,No,No,No,No,Public Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD

In [65]:
df

,record_id,company,city,location,area,workspace_type,target_segment,seat_capacity,price_per_seat_month,day_pass_price,...,air_conditioning,printing,event_space,community_events,managed_office,build_to_suit,enterprise_solution,data_source,data_date,data_type
0,1164,Regus,Indore,Regus Indore,Vijay Nagar,Private Office,Freelancer,10,18300,465,...,Yes,No,Yes,YES,NaN,Y,Yes,Company Website,2026-09-27,SYNTHETIC_PRACTICE_RECORD
1,1034,BizNest,Indore,BizNest Palasia,New Palasia,Hot Desk,Enterprise,60,6100,886 + GST,...,Yes,Yes,Yes,NaN,NO,No,NO,Public Listing,2026-09-29,SYNTHETIC_PRACTICE_RECORD
2,1016,Nexus Spaces,Indore,Vishal Cube,Janjeerwala Square,Private Office,SME,10,"₹11,500",1016,...,Yes,Yes,YES,yes,Yes,No,NaN,Company Website,2026-09-29,SYNTHETIC_PRACTICE_RECORD
3,1323,IndiQube,Indore,IndiQube Indore,Vijay Nagar,Private Office,Enterprise,8,14700,540,...,Yes,Yes,no,No,NaN,NaN,No,Marketplace Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD
4,1058,Nexus Spaces,Indore,Nexus Hub,Vijay Nagar,Private Office,Remote Team,4,8200,811,...,Yes,NaN,Yes,No,No,No,No,Public Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,1072,Nexus Spaces,Indore,Nexus Central,New Palasia,Private Office,Consultant,2,9100,₹675,...,Y,NO,N,Yes,Yes,NaN,No,Company Website,2026-09-25,SYNTHETIC_PRACTICE_RECORD
358,1107,Smartworks,Indore,Brilliant Centre,New Palasia,Private Office,Startup,12,16500,311,...,Yes,Yes,No,N,No,Yes,NaN,Public Listing,2026-09-29,SYNTHETIC_PRACTICE_RECORD
359,1271,Cowork Studio,Indore,Cowork Studio North,Vijay Nagar,Dedicated Desk,Startup,40,7700,NaN,...,Y,NaN,N,NaN,NO,No,NaN,Company Website,2026-09-28,SYNTHETIC_PRACTICE_RECORD
360,1349,Smartworks,Indore,Smartworks Indore,Vijay Nagar,Enterprise Office,Remote Team,150,"33,500",₹976,...,Y,YES,No,No,Yes,NaN,Yes,Public Listing,2026-09-29,SYNTHETIC_PRACTICE_RECORD
361,1103,Awfis,Indore,Apollo Premier,Vijay Nagar,Hot Desk,Enterprise,20,NaN,NaN,...,NaN,Yes,NaN,No,NaN,No,N,Public Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD

In [66]:
df.head()

,record_id,company,city,location,area,workspace_type,target_segment,seat_capacity,price_per_seat_month,day_pass_price,...,air_conditioning,printing,event_space,community_events,managed_office,build_to_suit,enterprise_solution,data_source,data_date,data_type
0,1164,Regus,Indore,Regus Indore,Vijay Nagar,Private Office,Freelancer,10,18300,465,...,Yes,No,Yes,YES,NaN,Y,Yes,Company Website,2026-09-27,SYNTHETIC_PRACTICE_RECORD
1,1034,BizNest,Indore,BizNest Palasia,New Palasia,Hot Desk,Enterprise,60,6100,886 + GST,...,Yes,Yes,Yes,NaN,NO,No,NO,Public Listing,2026-09-29,SYNTHETIC_PRACTICE_RECORD
2,1016,Nexus Spaces,Indore,Vishal Cube,Janjeerwala Square,Private Office,SME,10,"₹11,500",1016,...,Yes,Yes,YES,yes,Yes,No,NaN,Company Website,2026-09-29,SYNTHETIC_PRACTICE_RECORD
3,1323,IndiQube,Indore,IndiQube Indore,Vijay Nagar,Private Office,Enterprise,8,14700,540,...,Yes,Yes,no,No,NaN,NaN,No,Marketplace Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD
4,1058,Nexus Spaces,Indore,Nexus Hub,Vijay Nagar,Private Office,Remote Team,4,8200,811,...,Yes,NaN,Yes,No,No,No,No,Public Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD

In [67]:
df.shape

(362, 34)

In [68]:
df.columns

Index(['record_id', 'company', 'city', 'location', 'area', 'workspace_type',
       'target_segment', 'seat_capacity', 'price_per_seat_month',
       'day_pass_price', 'meeting_room_price_hour', 'private_office_available',
       'dedicated_desk', 'hot_desk', 'virtual_office', 'meeting_room',
       'conference_room', 'wifi', 'parking', 'power_backup', 'cafeteria',
       'housekeeping', 'security', '24x7_access', 'air_conditioning',
       'printing', 'event_space', 'community_events', 'managed_office',
       'build_to_suit', 'enterprise_solution', 'data_source', 'data_date',
       'data_type'],
      dtype='str')

In [69]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 34 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   record_id                 362 non-null    int64
 1   company                   362 non-null    str
 2   city                      362 non-null    str
 3   location                  362 non-null    str
 4   area                      362 non-null    str
 5   workspace_type            362 non-null    str
 6   target_segment            362 non-null    str
 7   seat_capacity             362 non-null    int64
 8   price_per_seat_month      339 non-null    str
 9   day_pass_price            333 non-null    str
 10  meeting_room_price_hour   331 non-null    str
 11  private_office_available  342 non-null    str
 12  dedicated_desk            317 non-null    str
 13  hot_desk                  331 non-null    str
 14  virtual_office            320 non-null    str
 15  meeting_room              311 non-null    str
 16  conference_room           301 non-null    str
 17  wifi                      314 non-null    str
 18  parking                   319 non-null    str
 19  power_backup              307 non-null    str
 20  cafeteria                 290 non-null    str
 21  housekeeping              317 non-null    str
 22  security                  300 non-null    str
 23  24x7_access               303 non-null    str
 24  air_conditioning          309 non-null    str
 25  printing                  311 non-null    str
 26  event_space               312 non-null    str
 27  community_events          302 non-null    str
 28  managed_office            327 non-null    str
 29  build_to_suit             314 non-null    str
 30  enterprise_solution       316 non-null    str
 31  data_source               362 non-null    str
 32  data_date                 362 non-null    str
 33  data_type                 362 non-null    str
dtypes: int64(2), str(32)
memory usage: 157.8 KB

In [70]:
df.describe(include="all")

,record_id,company,city,location,area,workspace_type,target_segment,seat_capacity,price_per_seat_month,day_pass_price,...,air_conditioning,printing,event_space,community_events,managed_office,build_to_suit,enterprise_solution,data_source,data_date,data_type
count,362.000000,362,362,362,362,362,362,362.000000,339,333,...,309,311,312,302,327,314,316,362,362,362
unique,NaN,12,1,30,9,8,6,NaN,263,295,...,8,8,8,8,8,8,8,4,5,1
top,NaN,Workie,Indore,IndiQube Indore,Vijay Nagar,Managed Office,SME,NaN,7900,1037,...,Yes,Yes,Yes,Yes,Yes,No,No,Manual Research,2026-09-28,SYNTHETIC_PRACTICE_RECORD
freq,NaN,54,362,20,209,80,69,NaN,4,5,...,190,153,110,99,201,169,148,108,81,362
mean,1176.513812,NaN,NaN,NaN,NaN,NaN,NaN,38.535912,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,101.760084,NaN,NaN,NaN,NaN,NaN,NaN,42.281016,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1001.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1088.250000,NaN,NaN,NaN,NaN,NaN,NaN,10.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1176.500000,NaN,NaN,NaN,NaN,NaN,NaN,20.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1264.750000,NaN,NaN,NaN,NaN,NaN,NaN,50.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1350.000000,NaN,NaN,NaN,NaN,NaN,NaN,200.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

cafeteria                   72
security                    62
conference_room             61
community_events            60
24x7_access                 59
power_backup                55
air_conditioning            53
printing                    51
meeting_room                51
event_space                 50
wifi                        48
build_to_suit               48
enterprise_solution         46
dedicated_desk              45
housekeeping                45
parking                     43
virtual_office              42
managed_office              35
meeting_room_price_hour     31
hot_desk                    31
day_pass_price              29
price_per_seat_month        23
private_office_available    20
dtype: int64

In [72]:
missing_percent = (
    df.isnull().mean() * 100
).sort_values(ascending=False)

missing_percent[missing_percent > 0]

cafeteria                   19.889503
security                    17.127072
conference_room             16.850829
community_events            16.574586
24x7_access                 16.298343
power_backup                15.193370
air_conditioning            14.640884
meeting_room                14.088398
printing                    14.088398
event_space                 13.812155
wifi                        13.259669
build_to_suit               13.259669
enterprise_solution         12.707182
housekeeping                12.430939
dedicated_desk              12.430939
parking                     11.878453
virtual_office              11.602210
managed_office               9.668508
meeting_room_price_hour      8.563536
hot_desk                     8.563536
day_pass_price               8.011050
price_per_seat_month         6.353591
private_office_available     5.524862
dtype: float64

In [73]:
df.duplicated().sum()

np.int64(12)

In [74]:
duplicates = df[df.duplicated(keep=False)]

duplicates.head(20)

,record_id,company,city,location,area,workspace_type,target_segment,seat_capacity,price_per_seat_month,day_pass_price,...,air_conditioning,printing,event_space,community_events,managed_office,build_to_suit,enterprise_solution,data_source,data_date,data_type
26,1219,IndiQube,Indore,IndiQube Indore,Vijay Nagar,Managed Office,Enterprise,75,22300,990,...,Yes,No,No,Yes,Yes,Yes,No,Public Listing,2026-09-25,SYNTHETIC_PRACTICE_RECORD
29,1343,Nexus Spaces,Indore,Nexus Hub,Vijay Nagar,Private Office,SME,10,8800,531,...,N,No,NaN,Yes,No,No,no,Manual Research,2026-09-26,SYNTHETIC_PRACTICE_RECORD
75,1263,Nexus Spaces,Indore,Nexus Central,New Palasia,Private Office,Consultant,6,15800,1037,...,Yes,Yes,YES,NaN,NaN,No,No,Public Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD
78,1044,WorkSpace 24,Indore,WorkSpace 24 Central,Vijay Nagar,Hot Desk,SME,50,₹ 7200/month,₹495,...,Yes,No,No,NaN,No,No,No,Manual Research,2026-09-27,SYNTHETIC_PRACTICE_RECORD
102,1276,WeWork,Indore,WeWork Indore,Vijay Nagar,Meeting Room,Freelancer,4,"6,100",₹379,...,NaN,Yes,No,No,No,No,Yes,Manual Research,2026-09-25,SYNTHETIC_PRACTICE_RECORD
107,1173,Regus,Indore,Regus Business Centre,MG Road,Hot Desk,SME,30,10100,623,...,Yes,No,NO,NaN,No,NaN,No,Marketplace Listing,2026-09-27,SYNTHETIC_PRACTICE_RECORD
130,1173,Regus,Indore,Regus Business Centre,MG Road,Hot Desk,SME,30,10100,623,...,Yes,No,NO,NaN,No,NaN,No,Marketplace Listing,2026-09-27,SYNTHETIC_PRACTICE_RECORD
134,1007,Workie,Indore,Omega Tower,Vijay Nagar,Dedicated Desk,Consultant,40,"11,900",352,...,NaN,no,Yes,Y,Yes,NaN,No,Public Listing,2026-09-27,SYNTHETIC_PRACTICE_RECORD
135,1263,Nexus Spaces,Indore,Nexus Central,New Palasia,Private Office,Consultant,6,15800,1037,...,Yes,Yes,YES,NaN,NaN,No,No,Public Listing,2026-09-28,SYNTHETIC_PRACTICE_RECORD
152,1276,WeWork,Indore,WeWork Indore,Vijay Nagar,Meeting Room,Freelancer,4,"6,100",₹379,...,NaN,Yes,No,No,No,No,Yes,Manual Research,2026-09-25,SYNTHETIC_PRACTICE_RECORD
189,1341,WeWork,Indore,WeWork Indore,Vijay Nagar,Private Office,Remote Team,8,18300,1037,...,NaN,Yes,No,Yes,No,NO,yes,Public Listing,2026-09-26,SYNTHETIC_PRACTICE_RECORD
213,1295,Workie,Indore,Omega Tower,Vijay Nagar,Managed Office,Startup,50,13800,460,...,NO,NaN,No,NO,Yes,N,No,Public Listing,2026-09-26,SYNTHETIC_PRACTICE_RECORD
220,1066,Regus,Indore,Regus Business Centre,MG Road,Hot Desk,Remote Team,60,₹ 5100/month,₹814,...,Yes,Yes,NO,NaN,Yes,No,Yes,Manual Research,2026-09-28,SYNTHETIC_PRACTICE_RECORD
240,1341,WeWork,Indore,WeWork Indore,Vijay Nagar,Private Office,Remote Team,8,18300,1037,...,NaN,Yes,No,Yes,No,NO,yes,Public Listing,2026-09-26,SYNTHETIC_PRACTICE_RECORD
250,1066,Regus,Indore,Regus Business Centre,MG Road,Hot Desk,Remote Team,60,₹ 5100/month,₹814,...,Yes,Yes,NO,NaN,Yes,No,Yes,Manual Research,2026-09-28,SYNTHETIC_PRACTICE_RECORD
275,1139,Smartworks,Indore,Smartworks Indore,Vijay Nagar,Managed Office,Remote Team,20,19800,NaN,...,NaN,NaN,Yes,NaN,Yes,N,Yes,Public Listing,2026-09-27,SYNTHETIC_PRACTICE_RECORD
285,1343,Nexus Spaces,Indore,Nexus Hub,Vijay Nagar,Private Office,SME,10,8800,531,...,N,No,NaN,Yes,No,No,no,Manual Research,2026-09-26,SYNTHETIC_PRACTICE_RECORD
294,1139,Smartworks,Indore,Smartworks Indore,Vijay Nagar,Managed Office,Remote Team,20,19800,NaN,...,NaN,NaN,Yes,NaN,Yes,N,Yes,Public Listing,2026-09-27,SYNTHETIC_PRACTICE_RECORD
295,1307,Regus,Indore,Regus Indore,Vijay Nagar,Enterprise Office,SME,150,₹ 15400/month,500,...,Yes,No,No,Y,Yes,N,Yes,Manual Research,2026-09-25,SYNTHETIC_PRACTICE_RECORD
299,1044,WorkSpace 24,Indore,WorkSpace 24 Central,Vijay Nagar,Hot Desk,SME,50,₹ 7200/month,₹495,...,Yes,No,No,NaN,No,No,No,Manual Research,2026-09-27,SYNTHETIC_PRACTICE_RECORD

In [75]:
df = df.drop_duplicates()

In [76]:
df.duplicated().sum()

np.int64(0)

In [77]:
df.shape

(350, 34)

In [78]:
df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [79]:
df.columns.tolist()

['record_id',
 'company',
 'city',
 'location',
 'area',
 'workspace_type',
 'target_segment',
 'seat_capacity',
 'price_per_seat_month',
 'day_pass_price',
 'meeting_room_price_hour',
 'private_office_available',
 'dedicated_desk',
 'hot_desk',
 'virtual_office',
 'meeting_room',
 'conference_room',
 'wifi',
 'parking',
 'power_backup',
 'cafeteria',
 'housekeeping',
 'security',
 '24x7_access',
 'air_conditioning',
 'printing',
 'event_space',
 'community_events',
 'managed_office',
 'build_to_suit',
 'enterprise_solution',
 'data_source',
 'data_date',
 'data_type']

In [80]:
text_columns = df.select_dtypes(include="object").columns

text_columns

C:\Users\sujal\AppData\Local\Temp\ipykernel_35544\3066221282.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Index(['company', 'city', 'location', 'area', 'workspace_type',
       'target_segment', 'price_per_seat_month', 'day_pass_price',
       'meeting_room_price_hour', 'private_office_available', 'dedicated_desk',
       'hot_desk', 'virtual_office', 'meeting_room', 'conference_room', 'wifi',
       'parking', 'power_backup', 'cafeteria', 'housekeeping', 'security',
       '24x7_access', 'air_conditioning', 'printing', 'event_space',
       'community_events', 'managed_office', 'build_to_suit',
       'enterprise_solution', 'data_source', 'data_date', 'data_type'],
      dtype='str')

In [81]:
for col in text_columns:
    df[col] = df[col].str.strip()

In [82]:
yes_no_columns = [
    "private_office_available",
    "dedicated_desk",
    "hot_desk",
    "virtual_office",
    "meeting_room",
    "conference_room",
    "wifi",
    "parking",
    "power_backup",
    "cafeteria",
    "housekeeping",
    "security",
    "24x7_access",
    "air_conditioning",
    "printing",
    "event_space",
    "community_events",
    "managed_office",
    "build_to_suit",
    "enterprise_solution"
]

In [83]:
for col in yes_no_columns:
    df[col] = (
        df[col]
        .astype("string")
        .str.strip()
        .str.lower()
        .map({
            "yes": "Yes",
            "y": "Yes",
            "no": "No",
            "n": "No"
        })
    )

In [84]:
df["wifi"].value_counts(dropna=False)

wifi
Yes    294
NaN     47
No       9
Name: count, dtype: int64

In [85]:
price_columns = [
    "price_per_seat_month",
    "day_pass_price",
    "meeting_room_price_hour"
]

In [86]:
for col in price_columns:
    df[col] = (
        df[col]
        .astype("string")
        .str.replace("₹", "", regex=False)
        .str.replace(",", "", regex=False)
        .str.replace("/month", "", regex=False)
        .str.replace("+ GST", "", regex=False)
        .str.strip()
    )

    df[col] = pd.to_numeric(
        df[col],
        errors="coerce"
    )

In [87]:
df[price_columns].dtypes

price_per_seat_month       Int64
day_pass_price             Int64
meeting_room_price_hour    Int64
dtype: object

In [88]:
df[price_columns].describe()

       price_per_seat_month  day_pass_price  meeting_room_price_hour
count                 327.0           322.0                    319.0
mean           11750.458716      701.481366               668.338558
std             7058.427811      228.984092               283.066205
min                   600.0           302.0                    300.0
25%                  6150.0          507.75                    400.0
50%                 10100.0           691.0                    600.0
75%                 16150.0           886.0                    900.0
max                 33700.0          1098.0                   1200.0

In [89]:
df[df["price_per_seat_month"] <= 0]

Empty DataFrame
Columns: [record_id, company, city, location, area, workspace_type, target_segment, seat_capacity, price_per_seat_month, day_pass_price, meeting_room_price_hour, private_office_available, dedicated_desk, hot_desk, virtual_office, meeting_room, conference_room, wifi, parking, power_backup, cafeteria, housekeeping, security, 24x7_access, air_conditioning, printing, event_space, community_events, managed_office, build_to_suit, enterprise_solution, data_source, data_date, data_type]
Index: []

[0 rows x 34 columns]

In [90]:
df["seat_capacity"] = pd.to_numeric(
    df["seat_capacity"],
    errors="coerce"
)

In [91]:
df["seat_capacity"].isnull().sum()

np.int64(0)

In [92]:
df["seat_capacity"].describe()

count    350.000000
mean      38.420000
std       42.367449
min        0.000000
25%       10.000000
50%       20.000000
75%       50.000000
max      200.000000
Name: seat_capacity, dtype: float64

In [93]:
df["data_date"] = pd.to_datetime(
    df["data_date"],
    errors="coerce"
)

In [94]:
df["data_date"].dtype

dtype('<M8[us]')

In [95]:
df["company"].value_counts()

company
Workie           52
Awfis            45
Nexus Spaces     33
Incuspaze        30
Regus            28
IndiQube         28
Smartworks       28
WorkSpace 24     25
Cowork Studio    24
BizNest          22
Smart Office     19
WeWork           16
Name: count, dtype: int64

In [96]:
df["workspace_type"].value_counts()

workspace_type
Managed Office       77
Private Office       75
Dedicated Desk       65
Hot Desk             50
Virtual Office       26
Enterprise Office    26
Meeting Room         19
Day Pass             12
Name: count, dtype: int64

In [97]:
df["target_segment"].value_counts()

target_segment
SME            65
Consultant     65
Remote Team    61
Enterprise     59
Freelancer     55
Startup        45
Name: count, dtype: int64

In [98]:
df["area"].value_counts()

area
Vijay Nagar           200
New Palasia            38
Scheme 54              29
AB Road                20
Janjeerwala Square     15
MG Road                14
Palasia                12
Rau                    12
Bhawarkua              10
Name: count, dtype: int64

In [99]:
quality_report = pd.DataFrame({
    "column": df.columns,
    "data_type": df.dtypes.astype(str).values,
    "missing_count": df.isnull().sum().values,
    "missing_percent": (
        df.isnull().mean().values * 100
    ).round(2),
    "unique_values": [
        df[col].nunique(dropna=True)
        for col in df.columns
    ]
})

quality_report

,column,data_type,missing_count,missing_percent,unique_values
0,record_id,int64,0,0.00,350
1,company,str,0,0.00,12
2,city,str,0,0.00,1
3,location,str,0,0.00,30
4,area,str,0,0.00,9
5,workspace_type,str,0,0.00,8
6,target_segment,str,0,0.00,6
7,seat_capacity,int64,0,0.00,19
8,price_per_seat_month,Int64,23,6.57,184
9,day_pass_price,Int64,28,8.00,274
10,meeting_room_price_hour,Int64,31,8.86,7
11,private_office_available,str,19,5.43,2
12,dedicated_desk,str,44,12.57,2
13,hot_desk,str,31,8.86,2
14,virtual_office,str,41,11.71,2
15,meeting_room,str,49,14.00,2
16,conference_room,str,58,16.57,2
17,wifi,str,47,13.43,2
18,parking,str,38,10.86,2
19,power_backup,str,52,14.86,2
20,cafeteria,str,69,19.71,2
21,housekeeping,str,44,12.57,2
22,security,str,59,16.86,2
23,24x7_access,str,58,16.57,2
24,air_conditioning,str,49,14.00,2
25,printing,str,49,14.00,2
26,event_space,str,49,14.00,2
27,community_events,str,55,15.71,2
28,managed_office,str,34,9.71,2
29,build_to_suit,str,46,13.14,2
30,enterprise_solution,str,46,13.14,2
31,data_source,str,0,0.00,4
32,data_date,datetime64[us],0,0.00,5
33,data_type,str,0,0.00,1

In [100]:
missing_summary = pd.DataFrame({
    "missing_count": df.isnull().sum(),
    "missing_percent": (df.isnull().mean() * 100).round(2)
})

missing_summary = missing_summary[
    missing_summary["missing_count"] > 0
].sort_values(
    "missing_percent",
    ascending=False
)

missing_summary

                          missing_count  missing_percent
cafeteria                            69            19.71
security                             59            16.86
conference_room                      58            16.57
24x7_access                          58            16.57
community_events                     55            15.71
power_backup                         52            14.86
meeting_room                         49            14.00
event_space                          49            14.00
air_conditioning                     49            14.00
printing                             49            14.00
wifi                                 47            13.43
enterprise_solution                  46            13.14
build_to_suit                        46            13.14
dedicated_desk                       44            12.57
housekeeping                         44            12.57
virtual_office                       41            11.71
parking                              38            10.86
managed_office                       34             9.71
meeting_room_price_hour              31             8.86
hot_desk                             31             8.86
day_pass_price                       28             8.00
price_per_seat_month                 23             6.57
private_office_available             19             5.43

In [101]:
price_columns = [
    "price_per_seat_month",
    "day_pass_price",
    "meeting_room_price_hour"
]

df[price_columns].isnull().sum()

price_per_seat_month       23
day_pass_price             28
meeting_room_price_hour    31
dtype: int64

In [102]:
df[price_columns].describe()

       price_per_seat_month  day_pass_price  meeting_room_price_hour
count                 327.0           322.0                    319.0
mean           11750.458716      701.481366               668.338558
std             7058.427811      228.984092               283.066205
min                   600.0           302.0                    300.0
25%                  6150.0          507.75                    400.0
50%                 10100.0           691.0                    600.0
75%                 16150.0           886.0                    900.0
max                 33700.0          1098.0                   1200.0

In [103]:
important_columns = [
    "company",
    "location",
    "area",
    "workspace_type",
    "target_segment",
    "seat_capacity"
]

df[important_columns].isnull().sum()

company           0
location          0
area              0
workspace_type    0
target_segment    0
seat_capacity     0
dtype: int64

In [104]:
df["company"].value_counts(dropna=False)

company
Workie           52
Awfis            45
Nexus Spaces     33
Incuspaze        30
Regus            28
IndiQube         28
Smartworks       28
WorkSpace 24     25
Cowork Studio    24
BizNest          22
Smart Office     19
WeWork           16
Name: count, dtype: int64

In [105]:
df["company"].isnull().sum()

np.int64(0)

In [106]:
df["workspace_type"].value_counts(dropna=False)

workspace_type
Managed Office       77
Private Office       75
Dedicated Desk       65
Hot Desk             50
Virtual Office       26
Enterprise Office    26
Meeting Room         19
Day Pass             12
Name: count, dtype: int64

In [107]:
df["workspace_type"].isnull().sum()

np.int64(0)

In [108]:
df["price_available"] = np.where(
    df["price_per_seat_month"].notna(),
    "Yes",
    "No"
)

In [109]:
df["price_available"].value_counts()

price_available
Yes    327
No      23
Name: count, dtype: int64

In [110]:
df["completeness_score"] = (
    df.notna().sum(axis=1) /
    len(df.columns)
) * 100

In [111]:
df["completeness_score"] = df["completeness_score"].round(2)

In [112]:
df["completeness_score"].describe()

count    350.000000
mean      91.682200
std        4.975866
min       74.290000
25%       88.570000
50%       91.430000
75%       94.290000
max      100.000000
Name: completeness_score, dtype: float64

In [113]:
df[
    ["company", "location", "workspace_type", "completeness_score"]
].head(10)

         company              location  workspace_type  completeness_score
0          Regus          Regus Indore  Private Office               94.29
1        BizNest       BizNest Palasia        Hot Desk               94.29
2   Nexus Spaces           Vishal Cube  Private Office               88.57
3       IndiQube       IndiQube Indore  Private Office               88.57
4   Nexus Spaces             Nexus Hub  Private Office               94.29
5   WorkSpace 24  WorkSpace 24 Central  Dedicated Desk               85.71
6   Smart Office      Smart Office Hub  Managed Office               88.57
7          Regus          Regus Indore  Dedicated Desk               94.29
8       IndiQube       IndiQube Indore  Virtual Office               94.29
9  Cowork Studio         Cowork Studio  Virtual Office               97.14

In [114]:
df["data_date"] = pd.to_datetime(
    df["data_date"],
    errors="coerce"
)

In [115]:
df["data_date"].dtype

dtype('<M8[us]')

In [116]:
df.to_csv("workie_competitor_cleaned.csv", index=False)